### ISSUE TITLE
[portus] /secrets/portus.key shouldn't require chmod 644

### ISSUE THREAD

**Issue by bicquet** [openSUSE/docker-containers#44]
**docker image:** using the most recent successfully built _head_ from https://hub.docker.com/r/opensuse/portus/builds/bg5vakttezxqffqvlnfoupv/
opensuse/portus@sha256:31f79c09a33eb59b510dca4f595102e61572649fc239ab9595b35abcc03983a2

**issue:** when passing a custom private key into portus via a docker-compose volume, portus fails to authenticate a docker registry login (i.e. command line, not the portus web ui) unless the _private key_ has allowed read permissions for "other" (i.e. a non-root user). in the host filesystem both the .key and .crt are owned by root.

docker-compose.yml snippet: 
_(note: removing the read-only-ness of the mapped volume doesn't fix the issue)_
```
    volumes:
      - ./certs/registry.crt:/certificates/portus-ca.crt:ro
      - ./certs/registry.key:/secrets/portus.key:ro
      - ./portus/config-local.yml:/srv/Portus/config/config-local.yml:ro
```

docker-compose logging snippet:
```portus_1    | App 146 stdout: Started GET "/v2/token?account=USER&client_id=docker&offline_token=true&service=registry.CUSTOM.FQDN" for IP.ADD.RE.SS at 2017-03-14 15:53:39 +0000
portus_1    | App 146 stdout: Processing by Api::V2::TokensController#show as JSON
portus_1    | App 146 stdout:   Parameters: {"account"=>"USER", "client_id"=>"docker", "offline_token"=>"true", "service"=>"registry.CUSTOM.FQDN"}
portus_1    | App 146 stdout: Completed 500 Internal Server Error in 65ms (ActiveRecord: 6.8ms)
portus_1    | App 146 stdout:
portus_1    | App 146 stdout: Errno::EACCES (Permission denied @ rb_sysopen - /secrets/portus.key):
portus_1    | App 146 stdout:   lib/portus/jwt_token.rb:49:in `binread'
portus_1    | App 146 stdout:   lib/portus/jwt_token.rb:49:in `private_key'
portus_1    | App 146 stdout:   lib/portus/jwt_token.rb:22:in `encoded_hash'
portus_1    | App 146 stdout:   app/controllers/api/v2/tokens_controller.rb:31:in `show'
portus_1    | App 146 stdout:
portus_1    | App 146 stdout:
portus_1    | App 146 stdout: Processing by ErrorsController#show as JSON
portus_1    | App 146 stdout:   Parameters: {"account"=>"USER", "client_id"=>"docker", "offline_token"=>"true", "service"=>"registry.CUSTOM.FQDN", "status"=>"500"}
portus_1    | App 146 stdout: Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.0ms)
portus_1    | App 130 stderr: Error during failsafe response: Missing template errors/500, application/500 with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim]}. Searched in:
portus_1    | App 130 stderr:   * "/srv/Portus/app/views"
portus_1    | App 130 stderr:   * "/srv/Portus/vendor/bundle/ruby/2.1.0/gems/kaminari-0.16.3/app/views"
portus_1    | App 130 stderr:   * "/srv/Portus/vendor/bundle/ruby/2.1.0/gems/devise-3.5.1/app/views"```

**Comment by flavio** [comment]
ping @mssola

**Comment by mssola** [comment]
I'll investigate this.

**Comment by decayofmind** [comment]
Facing this issue as well. Any update on this?

**Comment by mssola** [comment]
I believe this issue can no longer be reproduced. I'll close it now, but feel free to re-open it back again if you are still facing it.
